@startuml Labyrinthe
left to right direction

actor "Utilisateur" as us
actor "Système" as sy

rectangle Labyrinthe #lightyellow {
  usecase "Jouer" as UC1
  usecase "Commencer une partie" as UC2
  usecase "Se déplacer\ndans le labyrinthe" as UC3
  usecase "Afficher la progression" as UC4
  usecase "Sauvegarder la progression" as UC5
  usecase "Charger une partie" as UC6
  usecase "Lancer en mode progression" as UC7
}

' Relations principales (acteur -> cas d'utilisation)
us --> UC1
us --> UC2
us --> UC3
us --> UC4
us --> UC6
us --> UC7

sy --> UC5
@enduml
